package(
    default_visibility = [
        "//visibility:public",
    ],
)

cc_library(
    name = "user_info_dao",
    srcs = ["user_info_dao.cc"],
    hdrs = ["user_info_dao.h"],
    deps = [
        "//lib/domain:user_info",
        "//lib/util:db_util",
    ],
)
